### ISSUE TITLE
FileNotFoundError: [Errno 2]protein.faa

### ISSUE THREAD

**Issue by CBT127** [GreyGuoweiChen/RNA_virus_detector#3]
Thank you for making this convinient tool!But when I use VirBot I met this problem:
`$ VirBot.py --input ERR1992810.contigs.fa --output ERR1992810_vb --sen
Input contig: ERR1992810.contigs.fa
Output directory: ERR1992810_vb
Mode: sensitive mode
Predicting the encoded proteins...
Proteins prediction finished.
Scanning the protein by hmmsearch...

Error: Failed to open sequence file ERR1992810_vb/tmp/protein.faa for reading

HMMER finshed.
Scanning the protein by DIAMOND...
DIAMOND finshed.
Traceback (most recent call last):
  File "/home/tool/VirBot/VirBot.py", line 379, in <module>
    sen=args.sen, taxa_mode = args.taxa)
  File "/home/tool/VirBot/VirBot.py", line 309, in predict
    proteins = parse_protein(temp_dir + "protein.faa")
  File "/home/tool/VirBot/VirBot.py", line 171, in parse_protein
    with open(filename,'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'ERR1992810_vb/tmp/protein.faa'
`
Do you know how to solve it?And I have one more question want to know is will you update the ref database file? Thank you very much!

**Comment by GreyGuoweiChen** [comment]
Hello CBT,

Thanks for your comment. I suppose this is because the gene prediction step is not fulfilled and VirBot does not get any proteins as input. Please check the dependant package "Prodigal". if it is not accessible, we will get this error. By the way, have you ever checked the example shown in the guideline? That would be a better test case.

You could type _prodigal_ in your command line to check. And then have a try in the test case.

Guowei

**Comment by CBT127** [comment]
Thank you for your advice! I try it and it works!

**Comment by CBT127** [comment]
Do you know how to export the result of sequences of ncbi taxid?Thanks again!
